"""Initial migration

Revision ID: eb42bf9701b0
Revises: 
Create Date: 2024-11-12 05:07:00.418527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb42bf9701b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data')
    op.drop_table('y')
    op.drop_table('x')
    op.drop_index('ix_items_description', table_name='items')
    op.drop_column('items', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_items_description', 'items', ['description'], unique=False)
    op.create_table('x',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='numbers_pkey')
    )
    op.create_table('y',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dt', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='y_pkey')
    )
    op.create_table('weather_data',
    sa.Column('request_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_lat', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('location_lon', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('location_timezone_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_localtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location_localtime_epoch', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('location_utc_offset', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('observation_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weather_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weather_icon', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weather_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wind_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wind_degree', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wind_dir', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pressure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precip', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True),
    sa.Column('humidity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cloudcover', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feelslike', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uv_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_day', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
